### ISSUE TITLE
dashboard: sidebar is not tracking /apis highlight

### ISSUE THREAD

**Issue by guilhermerodz** [unkeyed/unkey#1981]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

https://github.com/user-attachments/assets/d3b1e4ec-d682-45b9-bec7-d9811addcbf4

### Steps to Reproduce

1. Go to /apis
2. Click on an existing API
3. Sidebar is now not highlighting "APIs"

### Expected behavior

Sidebar should highlight the "APIs" path while the user is visiting anything within /apis

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilhermerodz** [comment]
This should be fixed by #1973 since `/keys` will no longer exist and live inside `/api/.../keys`
