### ISSUE TITLE
Adding a link to the roadmap on the landing page.

### ISSUE THREAD

**Issue by harshsbhat** [unkeyed/unkey#2167]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

Currently, there is no way for anyone to know where/what the roadmap is except Discord. Adding a link for that on the landing page can help someone learn about upcoming features. 

https://unkey.productlane.com/roadmap

### Describe the solution

I don't have a layout/plan where we should add the link to the roadmap. But the navbar sounds like the most logical option.

**Comment by chronark** [comment]
We need to figure out what we want to do with the roadmap I think. I'm not happy with the current state.
cc @perkinsjr

**Comment by harshsbhat** [comment]
> We need to figure out what we want to do with the roadmap I think. I'm not happy with the current state. cc @perkinsjr

I believe the branding could be improved. For example, adding a roadmap to unkey.com/roadmap would help rather than keeping it on productlane website. Also, the blue color being used on roadmap doesn’t match the existing design on the Unkey landing page or dashboard. Finally, I suggest adding a link to the roadmap on the Unkey landing page. I would also love to see the link in the feedback card too that we recently added in the desktop sidebar.

These are just my suggestions, and I’m not trying to criticize you on a personal or professional level. I hope it didn’t come across that way.

**Comment by chronark** [comment]
no need to apologize, open feedback is great!
we're not super happy with productlane in general, so the first thing we need to figure out is if we want to get rid of it or double down

**Comment by perkinsjr** [comment]
Yeah productlane needs to be replaced. It doesn't work with the way we work.

This is in my discussion for next week

**Comment by harshsbhat** [comment]
What are your needs exactly? If you don't mind revealing it. I see a potential side project idea here.

**Comment by chronark** [comment]
we're going to use github discussions


cc @mcstepp, can you close this issue when we're done?

**Comment by chronark** [comment]
/award 150, closing this in favor of #2288
