### ISSUE TITLE
Add Link To Roadmap to WWW Footer

### ISSUE THREAD

**Issue by mcstepp** [unkeyed/unkey#2288]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

Unkey has moved their roadmap to Github Discussions. In an effort to be more publicly visible and transparent with our roadmap, we want to an easily accessible link to it on the the Unkey website. 

### Describe the solution

Given a visitor to `www.unkey.com`: 
- when I scroll to the bottom of the page, I expect to see a link to `www.unkey.com/roadmap` under "Company."
- when I click the link, I expect to be redirected to `https://github.com/unkeyed/unkey/discussions/categories/roadmap`

**Technical details**: 
- should be a Next.js redirect like our Discord and Github links in the footer

**Comment by harshsbhat** [comment]
@mcstepp #2167. I already had this open

**Comment by mcstepp** [comment]
@harshsbhat nice! gave you points and closed the issue so we only have the one, and increased the scoped since we did a little more work to the roadmap in general

**Comment by harshsbhat** [comment]
thanks @mcstepp for the points. I am working on this issue. /assign is not working for some reason. But should be able to get the PR in 10-15 minutes.

**Comment by chronark** [comment]
the issue didn't have the label, try again
